# Generated by Django 4.0.6 on 2022-07-15 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_cardvalues_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardvalues',
            name='category',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
            preserve_default=False,
        ),
    ]
